### ISSUE TITLE
Install fails on Mac

### ISSUE THREAD

**Issue by tsangiotis** [opendevelop/opendevelop#11]
``` bash
sudo python install/installer.py
```

Gives output:

``` bash
Creating user and group opendevelop...
Traceback (most recent call last):
  File "install/installer.py", line 35, in <module>
    if (call(['useradd', USER_NAME, '-U'])):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by parisk** [comment]
OpenDevelop right now supports only installation on Linux systems and preferably Ubuntu systems. A Mac-compatible installer can be created but is not a high-priority task. Community contribution is always welcome though.

**Note**: Even if a Mac compatible installer comes, OpenDevelop would require running Docker in an external Linux server to run code, since Docker runs only on Linux.

I do not close this issue, since I think it is a really nice idea, to have OpenDevelop on Macs, in the midterm future.
