### ISSUE TITLE
Sandbox does not terminate after code execution.

### ISSUE THREAD

**Issue by tsangiotis** [opendevelop/opendevelop#12]
Using opendevelop-py I made [this](https://gist.github.com/tsagi/80f4692cc5a3cecaba0c#file-od-py) simple script to test stuff but the output is:

``` bash
razor:~ tsagi$ python od.py
The image is:
razorTestImage
Creating sandbox...
Sandbox Slug is:
bb65f488b6e3cccb
Retrieving data...
Traceback (most recent call last):
  File "od.py", line 14, in <module>
    data = client.sandbox(sslug)
  File "/Library/Python/2.7/site-packages/opendevelop/opendevelop.py", line 111, in sandbox
    return self.authenticated_request('get', resource)
  File "/Library/Python/2.7/site-packages/opendevelop/opendevelop.py", line 73, in authenticated_request
    response = self.request(method, resource, payload, headers, files)
  File "/Library/Python/2.7/site-packages/opendevelop/opendevelop.py", line 59, in request
    response.raise_for_status()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 576, in raise_for_status
    raise http_error
requests.exceptions.HTTPError: 500 Server Error: None
```

Looking at the admin of my remote opendevelop instance I see that the sandbox I use is running. When I terminate it from there I don't get an error but there is no output in the logs.

**Comment by parisk** [comment]
Could you please supply information about the operating system on which you run OpenDevelop?

**Comment by tsangiotis** [comment]
It is an Ubuntu Server 12.04.3

**Comment by parisk** [comment]
This seems to work fine for the current release. Closing.
